run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosec
    - ineffassign
    - unused
    - gosimple
    - typecheck
    - structcheck
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  modules-download-mode: readonly
  tests: true
  timeout: 5m
#noinspection: disable some linters in generated code
linters-settings:
  gosec:
    # disable G104 (CWE-78) for tests that intentionally use shelling
    exclude:
      - G104